name: PR checks

on:
  pull_request: {}
  push:
    branches:
      - master
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: write
  actions: write
  pull-requests: write

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0

  setup:
    runs-on: ubuntu-latest
    needs: [cancel]
    outputs:
      python_version: ${{ steps.set_var.outputs.python_version }}
      poetry_version: ${{ steps.set_var.outputs.poetry_version }}
    steps:
      - id: set_var
        run: |
          echo "python_version=3.8" >> $GITHUB_OUTPUT
          echo "poetry_version=1.7.1" >> $GITHUB_OUTPUT

  perform-ruff-formatting:
    needs: [setup]
    uses: ./.github/workflows/formatter.yml
    secrets: inherit

  cache-dependencies:
    needs: [setup, perform-ruff-formatting]
    uses: ./.github/workflows/_cache-dependencies.yml
    secrets: inherit
    with:
      python_version: ${{ needs.setup.outputs.python_version }}
      poetry_version: ${{ needs.setup.outputs.poetry_version }}

  run-unit-test-versions:
    needs: [setup]
    uses: ./.github/workflows/ci_full.yml

  run-unit-test-per-database:
    needs: [setup]
    uses: ./.github/workflows/ci.yml

  # publish-data-platform-data-diff:
  #   needs:
  #     - setup
  #     - run-unit-test-versions
  #     - run-unit-test-per-database
  #     - cache-dependencies
  #   uses: ./.github/workflows/_publish-data-platform-data-diff.yml
  #   secrets: inherit
  #   with:
  #     python_version: ${{ needs.setup.outputs.python_version }}
  #     poetry_version: ${{ needs.setup.outputs.poetry_version }}
  #     python_cache_key: ${{ needs.cache-dependencies.outputs.python_cache_key }}
