name: formatter

on:
  workflow_dispatch:
  workflow_call:

jobs:
  linter_name:
    name: runner / ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check files using the ruff formatter
        uses: chartboost/ruff-action@v1
        id: ruff_formatter
        with:
          args: format
